fix: add explicit type annotations for `getWalletClient()` returns (#381)
* fix: add explicit type annotations for `getWalletClient()` returns

Without type inference only, the output of `pnpm build` will look like:
```typescript
declare class MockConnector extends Connector<MockProvider, MockConnectorOptions> {
    // ...
    getWalletClient(): Promise<{
        chain: viem.Chain;
        key: string;
        name: string;
        pollingInterval: number;
        request: viem.EIP1193RequestFn<viem.WalletRpcSchema>;
        transport: viem.TransportConfig<string, viem.EIP1193RequestFn> & Record<string, any>;
        type: string;
        uid: string;
        addChain: (args: viem.AddChainParameters) => Promise<void>;
        deployContract: <TAbi extends readonly unknown[] | viem.Abi, TChainOverride extends viem.Chain | undefined>(args: viem.DeployContractParameters<TAbi, viem.Chain, viem.Account, TChainOverride>) => Promise<`0x${string}`>;
        getAddresses: () => Promise<viem.GetAddressesReturnType>;
        getChainId: () => Promise<number>;
        getPermissions: () => Promise<viem.GetPermissionsReturnType>;
        requestAddresses: () => Promise<viem.RequestAddressesReturnType>;
        requestPermissions: (args: {
            [x: string]: Record<string, any>;
            eth_accounts: Record<string, any>;
        }) => Promise<viem.RequestPermissionsReturnType>;
        sendTransaction: <TChainOverride_1 extends viem.Chain | undefined>(args: viem.SendTransactionParameters<viem.Chain, viem.Account, TChainOverride_1>) => Promise<`0x${string}`>;
        signMessage: (args: viem.SignMessageParameters<viem.Account>) => Promise<`0x${string}`>;
        signTypedData: // ...;
        switchChain: (args: viem.SwitchChainParameters) => Promise<void>;
        watchAsset: (args: viem.WatchAssetParams) => Promise<boolean>;
        writeContract: <TAbi_1 extends readonly unknown[] | viem.Abi, TFunctionName extends string, TChainOverride_2 extends viem.Chain | undefined>(args: viem.WriteContractParameters<TAbi_1, TFunctionName, viem.Chain, viem.Account, TChainOverride_2>) => Promise<`0x${string}`>;
        account: viem.Account;
    }>;
```

This causes (@wagmi-dev/wagmi#2645):
```
error TS2322: Type 'MockConnector' is not assignable to type 'Connector<any, any>'.
  The types returned by 'getWalletClient(...)' are incompatible between these types.
    Type 'Promise<{ chain: Chain; key: string; name: string; pollingInterval: number; request: EIP1193RequestFn<WalletRpcSchema>; transport: TransportConfig<string, EIP1193RequestFn> & Record<...>; ... 15 more ...; account: Account; }>' is not assignable to type 'Promise<{ account: Account; batch?: { multicall?: boolean | MulticallBatchOptions | undefined; } | undefined; chain: Chain; key: string; name: string; ... 18 more ...; writeContract: <TAbi extends Abi | readonly unknown[], TFunctionName extends string, TChainOverride extends Chain | undefined>(args: WriteContractPar...'.
      Property 'extend' is missing in type '{ chain: Chain; key: string; name: string; pollingInterval: number; request: EIP1193RequestFn<WalletRpcSchema>; transport: TransportConfig<string, EIP1193RequestFn> & Record<...>; ... 15 more ...; account: Account; }' but required in type '{ account: Account; batch?: { multicall?: boolean | MulticallBatchOptions | undefined; } | undefined; chain: Chain; key: string; name: string; pollingInterval: number; ... 17 more ...; writeContract: <TAbi extends Abi | readonly unknown[], TFunctionName extends string, TChainOverride extends Chain | undefined>(args:...'.
```

The output should be:
```

declare class MockConnector extends Connector<MockProvider, MockConnectorOptions> {
    // ...
    getWalletClient(): Promise<WalletClient>;
}
```

* Create wicked-kiwis-speak.md

---------

Co-authored-by: jxom <jakemoxey@gmail.com>